---
uint8 levelflag
uint16 commversion                  # Old version Aliengo does not have
uint16 robotid                      # Old version Aliengo does not have
uint32 sn                           # Old version Aliengo does not have
uint8 bandwidth                     # Old version Aliengo does not have
uint8 mode
IMU imu
float32 forwardspeed
float32 sidespeed
float32 rotatespeed
float32 bodyheight
float32 updownspeed
float32 forwardposition       # (will be float type next version)   # Old version Aliengo is different
float32 sideposition    
Cartesian[4] footposition2body
Cartesian[4] footspeed2body
int16[4] footforce                  # Old version Aliengo is different
int16[4] footforceest               # Old version Aliengo does not have
uint32 tick               
uint8[40] wirelessremote
uint32 reserve                      # Old version Aliengo does not have
uint32 crc

# Under are not defined in SDK yet. # Old version Aliengo does not have
Cartesian[4] eeforce            # It's a 1-DOF force in real robot, but 3-DOF is better for visualization.
float32[12] jointp
