name: ci

on: [push, pull_request]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            distro: foxy
    env:
      UNITREE_LEGGED_SDK_PATH: /tmp/unitree_legged_sdk
      UNITREE_PLATFORM: "amd64"
    steps:
      - name: prepare unitree SDK
        run: |
          git clone https://github.com/unitreerobotics/unitree_legged_sdk $UNITREE_LEGGED_SDK_PATH
          cp -r $UNITREE_LEGGED_SDK_PATH/include/* /usr/local/include/
          cp -r $UNITREE_LEGGED_SDK_PATH/lib/* /usr/local/lib/

      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        #env: {ROS_DISTRO: "${{ matrix.distro }}" }
        env:
          ROS_DISTRO: "${{ matrix.distro }}"
          UNITREE_LEGGED_SDK_PATH: /tmp/unitree_legged_sdk
          UNITREE_PLATFORM: "amd64"
